botany/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    # Botany

    # Filters
    #url(r'^sample_search/', views.sample_search, name='sample_search'),
    # see https://www.dev2qa.com/django-filter-and-pagination-example/

    # overviews
    path('', views.allbotany, name='allbotany'),
    path('sample/', views.allsample, name='allsample'),

    path('species/manager', views.speciesmanager, name='speciesmanager'),
    path('species/manager/create', views.addspecies, name='addspecies'),

    # path('botany', views.botanyview, name='botanyview'),
    path('botanyoverview/sample/<int:sample_id>/flotation/<int:flotation_id>', views.botanyoverview, name='botanyoverview'),

    path('sample/flotation/', views.allflotation, name='allflotation'),
    path('flotation/<int:flotation_id>', views.allflotation, name='allflotation'),

    # listviews
    path('samplelist/', views.SampleListView.as_view(), name='samplelist'),

    # add
    path('addsample/', views.addsample, name='addsample'),

    re_path(r'^sample/addflotation/(?P<pk>\d+)/$', views.addflotation, name='addflotation'),
    re_path(r'^flotation/(?P<pk>\d+)/$', views.addlightresidue, name='addlightresidue'),
    re_path(r'^sample/(?P<fk>\d+)/flotation/(?P<pk>\d+)/$', views.addlightresidue, name='addlightresidue'),
    re_path(r'^sample/(?P<sp>\d+)/flotation/(?P<fk>\d+)/addcomposition/(?P<pk>\d+)/$', views.addcomposition, name='addcomposition'),



    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/lightresidue/(?P<fk>\d+)/composition/(?P<pk>\d+)/addfraction/', views.addfraction, name='addfraction'),
    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/composition/(?P<fk>\d+)/fraction/(?P<pk>\d+)/addplantpart/', views.addplantpart, name='addplantpart'),

    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/composition/(?P<fk>\d+)/fraction/(?P<pk>\d+)/addseed/', views.addseed, name='addseed'),

    # edit
    re_path('sample/edit/(?P<pk>\d+)/edit/', views.editsample, name='editsample'),

    re_path('flotation/edit/(?P<pk>\d+)/edit/', views.editflotation, name='editflotation'),
    re_path('sample/(?P<fk>\d+)/flotationform/edit/(?P<pk>\d+)/edit/', views.editflotationform, name='editflotationform'),


    re_path('sample/(?P<sp>\d+)/flotation/(?P<fk>\d+)/lightresidue/edit/(?P<pk>\d+)/edit/', views.editlightresidue, name='editlightresidue'),
    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/lightresidue/(?P<fk>\d+)/composition/edit/(?P<pk>\d+)/edit/', views.editcomposition, name='editcomposition'),


    # re_path('flotation/(?P<fk>\d+)/lightresidue/edit/(?P<pk>\d+)/edit/', views.editfraction, name='editfraction'),


    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/composition/(?P<fk>\d+)/fraction/edit/(?P<pk>\d+)/edit/', views.editfraction, name='editfraction'),

    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/fraction/(?P<fk>\d+)/plantpart/edit/(?P<pk>\d+)/edit/', views.editplantpart, name='editplantpart'),
    re_path('sample/(?P<sp>\d+)/flotation/(?P<fl>\d+)/fraction/(?P<fk>\d+)/seed/edit/(?P<pk>\d+)/edit/', views.editseed, name='editseed'),



    # details
    path('sample/<int:sample_id>/', views.detailsample, name='detailsample'),
    path('sample/flotation/<int:flotation_id>/', views.detailflotation, name='detailflotation'),
    path('flotation/lightresidue/<int:lightresidue_id>/', views.detaillightresidue, name='detaillightresidue'),
    # path('sample/flotation/lightresidue/<int:lightresidue_id>/', views.detaillightresidue, name='detaillightresidue'),

    path('flotation/lightresidue/<int:lightresidue_id>/composition/<int:composition_id>/', views.detailcomposition, name='detailcomposition'),

    path('flotation/composition/<int:composition_id>/fraction/<int:fraction_id>/', views.detailfraction, name='detailfraction'),



# path('addflotation/', views.addflotation, name='addflotation'),





]

depot/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from .views import detailstorage, allstorage, createstorage, editstorage, alllocation, detaillocation, createlocation, editlocation, SampleFliterView
from . import views

# from depot.views import SamplesListView, ContainerListView, LocationListView, JoinSampleContainerListView

urlpatterns = [
path('', SampleFliterView, name='SampleFliterView'),

url(r'^change_container/(?P<operation>.*)/(?P<pk>\d+)/sample/(?P<fk>\d+)$', views.change_container, name='change_container'),

# url(r'^container/(?P<operation>.*)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
# url(r'^containerx/<int:container_id>/(?P<operation>.*)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),

# EDIT

url(r'^storage/edit/(?P<pk>\d+)/edit/$', editstorage, name='editstorage'),
url(r'^location/edit/(?P<pk>\d+)/edit/$', editlocation, name='editlocation'),

#storage
re_path(r'^storage/$', allstorage, name='allstorage'),
path('storage/<int:store_id>/', detailstorage, name='detailstorage'),
#
url(r'^storage/createstorage/$', createstorage, name='createstorage'),


#locations
url(r'^location/$', alllocation, name='alllocation'),
path('location/<int:location_id>/', detaillocation, name='detaillocation'),
url(r'^createlocation/$', createlocation, name='createlocation'),


#container
url(r'^container/$', views.allcontainer, name='allcontainer'),
path('container/<int:container_id>/', views.detailcontainer, name='detailcontainer'),
# path('container/contents/<int:container_id>/', views.containercontents, name='containercontents'),
re_path(r'^editcontainercontents/edit/(?P<pk>\d+)/edit/$', views.editcontainercontents, name='editcontainercontents'),

re_path(r'^container/createcontainer/$', views.createcontainer, name='createcontainer'),
url(r'^container/edit/(?P<pk>\d+)/edit/$', views.editcontainer, name='editcontainer'),
# url(r'^container/search/edit/(?P<pk>\d+)/edit/$', views.editcontainersearch, name='editcontainersearch'),


# sample
path('alldepotsample', views.alldepotsample, name='alldepotsample'),
# path('alldepotsample/', views.SampleListView.as_view(), name='alldepotsample'),
re_path('assignsample/edit/(?P<pk>\d+)/edit/', views.assignsample, name='assignsample'),
path('sample/<int:sample_id>/', views.detaildepotsample, name='detaildepotsample'),
re_path('depotsample/edit/(?P<pk>\d+)/edit/', views.editdepotsample, name='editdepotsample'),
path('adddepotsample/', views.adddepotsample, name='adddepotsample'),
# path('containercontents/', views.containercontents, name='containercontents'),




# path('containercontentsdetail', views.containercontentsdetail, name='containercontentsdetail'),

# path('containerre_path(r'^containercontents/edit/(?P<pk>\d+)/edit/$', views.containercontents, name='containercontents'),contents/<int:pk>/', views.containercontents, name='containercontents'),


# url(r'^samples/filter/$', views.samplesearch, name='samplesearch'),
# url(r'^container/filter/$', views.containersearch, name='containersearch'),

# url(r'^container/page/$', views.containerpage, name='containerpage'),

# url(r'^samples/listing/$', views.listing, name='listing'),


# url(r'^sample_container_join/$', views.create_join_sample_container, name='create_join_sample_container'),
# url(r'^join_sample_container/create_join_sample_container/$', views.create_join_sample_container, name='create_join_sample_container'),
# url(r'^join_sample_container/edit/(?P<pk>\d+)/edit/$', views.edit_join_sample_container, name='edit_join_sample_container'),


# re_path(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),


]

kap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

import jobs.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('chat/', include('chat.urls', namespace='chat')),

    path('', jobs.views.home, name='home'),
    path('blog/', include('blog.urls')),

    path('trench/', include('trench.urls')),


    path('sample/', include('sample.urls')),
    path('botany/', include('botany.urls')),
	path('conservation/', include('conservation.urls')),
	path('zooarch/',include('zooarch.urls')),

    path('depot/',include(('depot.urls', 'depot'), namespace='depot')),

    #experimental
    path('experimental/', include('experimental.urls')),
    path('models3d/', include('models3d.urls')),

    # path('mapping/', include('mapping.urls')),

    path('spatial3d/', include('spatial3d.urls')),

    path('documentation/', include('documentation.urls')),
    path('teams/', include('teams.urls')),
    path('tickets/', include('tickets.urls')),
    path('settings/', include('settings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

botany/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from botany.choices import EASTING_CHOICES, NORTHING_CHOICES, RECOVERY_METHODS, MATERIALS, FRACTIONS

class Sample(models.Model):
    sample_id = models.AutoField(primary_key=True)
    area_easting = models.IntegerField(choices = EASTING_CHOICES)
    area_northing = models.IntegerField(choices = NORTHING_CHOICES)
    context_number = models.IntegerField()
    sample_number = models.IntegerField()
    # material_type = models.CharField(max_length=200, default='', blank=True, null=True, choices = MATERIALS)
    sample_type = models.CharField(max_length=200, default='', blank=True, null=True, choices = MATERIALS)
    weight = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=500, default='', blank=True, null=True)
    recovery_method = models.CharField(max_length=200, default='', blank=True, null=True, choices = RECOVERY_METHODS)
    taken_by = models.ForeignKey(settings.AUTH_USER_MODEL, db_column='taken_by', on_delete = models.PROTECT)
    # taken_by = models.ForeignKey(public.auth_user, db_column='taken_by', on_delete = models.PROTECT)
    comments = models.CharField(max_length=1000, default='', blank=True, null=True)

    def __str__(self):
        # return self.taken_by.first_name
        return str(self.sample_id)
        # return str(self.firstname)+ '-' +str(self.lastname)
        # return u'%s %s' % (self.first_name, self.last_name)


    class Meta:
        db_table = 'kap\".\"sample'
        ordering = ["sample_id"]
        managed = False
        #verbose_name_plural = "samples"


class Flotation(models.Model):
    flotation_id = models.AutoField(primary_key=True)
    sample_id = models.ForeignKey(Sample, db_column='sample_id', on_delete = models.PROTECT)
    # area_easting = models.IntegerField(choices = EASTING_CHOICES)
    # area_northing = models.IntegerField(choices = NORTHING_CHOICES)
    # context_number = models.IntegerField(blank=True, null=True)
    # sample_number = models.IntegerField(blank=True, null=True)
    flotation_date = models.DateTimeField(auto_now=False)
    entry_date = models.DateTimeField(auto_now_add=False)
    analyst_id = models.ForeignKey(settings.AUTH_USER_MODEL, db_column='analyst_id', on_delete = models.PROTECT)
    notes = models.CharField(max_length=600, default='', blank=True, null=True)

    def __str__(self):
        return str(self.flotation_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"flotation'
        #ordering = ["orderby"]
        verbose_name_plural = "Flotation"


class LightResidue(models.Model):
    lightresidue_id = models.AutoField(primary_key=True)
    flotation_id = models.ForeignKey(Flotation, db_column='flotation_id', on_delete = models.PROTECT)
    proportion_analysed = models.DecimalField(max_digits=5, decimal_places=3)
    soil_volume = models.DecimalField(max_digits=15, decimal_places=4)
    sample_volume = models.DecimalField(max_digits=15, decimal_places=4)
    sample_weight = models.DecimalField(max_digits=15, decimal_places=4)
    sediment = models.BooleanField()
    stone = models.BooleanField()
    roots = models.BooleanField()
    leaves = models.BooleanField()
    insect_parts = models.BooleanField()
    charred_dung = models.BooleanField()
    bone = models.BooleanField()
    shell = models.BooleanField()

    def __str__(self):
        return str(self.lightresidue_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"lightresidue'
        #ordering = ["orderby"]
        verbose_name_plural = "LightResidue"

class Composition(models.Model):
    composition_id = models.AutoField(primary_key=True)
    lightresidue_id = models.ForeignKey(LightResidue, db_column='lightresidue_id', on_delete = models.PROTECT)
    material_type = models.CharField(max_length=50, default='')
    type_count = models.DecimalField(max_digits=15, decimal_places=4)
    whole_weight = models.DecimalField(max_digits=15, decimal_places=4)
    fragment_weight = models.DecimalField(max_digits=15, decimal_places=4)

    def __str__(self):
        return str(self.composition_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"composition'
        #ordering = ["orderby"]
        verbose_name_plural = "Composition"

class Fraction(models.Model):
    fraction_id = models.AutoField(primary_key=True)
    composition_id = models.ForeignKey(Composition, db_column='composition_id', on_delete = models.PROTECT)
    fraction = models.CharField(max_length=20, choices = FRACTIONS)
    def __str__(self):
        return str(self.fraction_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"fraction'
        #ordering = ["orderby"]
        verbose_name_plural = "Fraction"

class Species(models.Model):
    species_id = models.AutoField(primary_key=True)
    taxon = models.CharField(max_length=50, blank=True, null=True)
    common_name = models.CharField(max_length=50, blank=True, null=True)
    species = models.CharField(max_length=50, blank=True, null=True)
    genus = models.CharField(max_length=50, blank=True, null=True)
    # family_name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return str(self.species)

    class Meta():
        managed=False
        db_table = 'kap\".\"plant_species'
        ordering = ["genus","species"]
        verbose_name_plural = "species"

class PlantPart(models.Model):
    plantpart_id = models.AutoField(primary_key=True)
    fraction_id = models.ForeignKey(Fraction, db_column='fraction_id', on_delete = models.PROTECT)
    species_id = models.ForeignKey(Species, db_column='species_id', on_delete = models.PROTECT, related_name='plant_species', blank=True, null=True)
    part = models.CharField(max_length=100)
    weight = models.DecimalField(max_digits=10, decimal_places=3)
    quantity = models.DecimalField(max_digits=10, decimal_places=3)


    def __str__(self):
        return str(self.plantpart_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"plant_part'
        #ordering = ["orderby"]
        verbose_name_plural = "plant parts"

class Seed(models.Model):
    seed_id = models.AutoField(primary_key=True)
    fraction_id = models.ForeignKey(Fraction, db_column='fraction_id', blank=True, null=True, on_delete = models.PROTECT)
    species_id = models.ForeignKey(Species, db_column='species_id', blank=True, null=True, on_delete = models.PROTECT, related_name='seed_species')
    weight_type = models.CharField(max_length=50)
    weight = models.DecimalField(max_digits=10, decimal_places=3)
    quantity_type = models.CharField(max_length=50)
    quantity = models.IntegerField()


    def __str__(self):
        return str(self.seed_id)

    class Meta():
        managed=False
        db_table = 'kap\".\"seed'
        ordering = ["species_id","fraction_id"]
        verbose_name_plural = "seeds"

botany/templates/dashboard/json_chart.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Django Highcharts Example</title>
</head>
<body>
  <div id="container" data-url="{% url 'chart_data' %}"></div>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
  <script>
    $.ajax({
      url: $("#container").attr("data-url"),
      dataType: 'json',
      success: function (data) {
        Highcharts.chart("container", data);
      }
    });
  </script>
</body>
</html>

botany/templates/dashboard/menu2.html
{% load staticfiles %}
<header>
  <div  class="fixed-top">
    <div class="navbar navbar-inverse navbar-static-top navbar-expand-lg navbar-dark bg-dark" id="topNav">
      <a class="navbar-brand" href="{% url 'home' %}">Gygaia V 0.1.7</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'allblogs' %}">Blog</a>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Depot</a>
            <div class="dropdown-menu " aria-labelledby="storage">
              <a class="dropdown-item" href="{% url 'depot:alldepotsample' %}">Samples</a>
              <a class="dropdown-item" href="{% url 'depot:allcontainer' %}">Containers</a>
              <a class="dropdown-item" href="{% url 'depot:alllocation' %}">Locations</a>
              <a class="dropdown-item" href="{% url 'depot:allstorage' %}">Depots</a>
              <!-- <a class="dropdown-item" href="#">Faunal</a>
              <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <a class="nav-item nav-link" href="{ url 'contextpage' }">Excavation</a>
          <div class="dropdown show">
            <a style="color:grey;" class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Photo Gallery</a>
            <div class="dropdown-menu " aria-labelledby="gallery">
              <a class="dropdown-item" href="{ url 'allimages' }">Photos_1</a>
              <hr />
              <!-- <a class="dropdown-item" href="#">Faunal</a>
              <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">3D Spatial</a>
            <div class="dropdown-menu " aria-labelledby="spatial3d">
              <a class="dropdown-item" href="{% url 'allphotobatch' %}">Photobatch</a>
              <hr />
              <!-- <a class="dropdown-item" href="#">Faunal</a>
              <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Botany</a>
            <div class="dropdown-menu " aria-labelledby="botany">
              <a class="dropdown-item" href="{% url 'samplelist' %}">Samples</a>
              <hr />
              <a class="dropdown-item" href="{% url 'speciesmanager' %}">Taxon Manager</a>
              <!-- <a class="dropdown-item" href="#">Faunal</a>
              <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Zooarch</a>
            <div class="dropdown-menu " aria-labelledby="samplesdropdown">
              <a class="dropdown-item" href="{ url 'allzooarch' }">Samples</a>
              <hr />
              <a class="dropdown-item" href="{% url 'allqnisp' %}">Qnisp</a>
              <!-- <a class="dropdown-item" href="{ url 'allzooarch' }">All Zooarch</a> -->
              <!-- <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Samples</a>
            <div class="dropdown-menu " aria-labelledby="samplesdropdown">
              <a class="dropdown-item" href="{ url 'allsamples' }">Samples</a>
              <hr />
              <a class="dropdown-item" href="{ url 'allzooarch' }">Faunal</a>
              <!-- <a class="dropdown-item" href="#">Conservation</a>
              <a class="dropdown-item" href="#">Ceramics</a>
              <a class="dropdown-item" href="#">Small Finds</a> -->
            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-comments" style="color:grey;"></i> <span style="color:grey;">[0]</span></a>
            <div class="dropdown-menu " aria-labelledby="messagedropdown">
              <a class="dropdown-item" href="% url '' %">Chat</a>
              <hr />
              <a class="dropdown-item" href="% url '' %">Alerts</a>
              <a class="dropdown-item" href="% url '' %">Questions</a>
            </div>
          </div>

          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-envelope" style="color:grey;"></i> <span style="color:grey;">[0]</span></a>

            <div class="dropdown-menu " aria-labelledby="alertdropdown">
              <a class="dropdown-item" href="% url '' %">Messages</a>
              <hr />
              <a class="dropdown-item" href="% url '' %">Alerts</a>
              <a class="dropdown-item" href="% url '' %">Questions</a>

            </div>
          </div>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user pr-2"></i>
              <!-- {{ user.get_username }} -->
              {{ user.get_full_name|default:user.username }}
            </a>
            <div class="dropdown-menu " aria-labelledby="dropdownMenuLink">
              <!-- <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a> -->
              <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
              <a class="dropdown-item" href="{% url 'alltickets' %}"><img src="{% static 'icon_sets\clipboard-list-solid.svg'%}" alt"" height="20px" width="20px" /> Tickets</a>
              <a class="dropdown-item" href="{% url 'overview' %}"><img src="{% static 'icon_sets\cogs-solid.svg'%}" alt"" height="20px" width="20px" /> Settings</a>
            </div>
          </div>
          {% else %}
          <a href="{% url 'login'%}?next={{request.path}}">Login</a>
          <a class="nav-item nav-link " href="#">next</a>
          {% endif %}
        </div>
        <div class="dropdown show">
          <a class="btn btn-secondary dropdown-toggle mr-2" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Experimental</a>
          <div class="dropdown-menu " aria-labelledby="samplesdropdown">
            <a class="dropdown-item" href="{% url 'webviewer3d' %}">webviewer3d</a>
            <hr />
            <a class="dropdown-item" href="{ url 'allzooarch' }">Faunal</a>
            <a class="dropdown-item" href="{% url 'models3d' %}">3d models</a>
            <!-- <a class="dropdown-item" href="#">Conservation</a>
            <a class="dropdown-item" href="#">Ceramics</a>
            <a class="dropdown-item" href="#">Small Finds</a> -->
          </div>
        </div>
      </div>

      <div class="navbar navbar-custom navbar-inverse navbar-static-top navbar-dark bg-dark" id="nav2">
        <div class="float-left">
          <a href="{% url 'allbotany' %}" style="color:white;"><button  type="button" class="btn btn-outline-info"><img src="{% static 'icon_sets\seedling-solid.svg'%}" alt"" height="65" width="68" /><br />Botany</button></a>
          <a href="{% url 'samplelist' %}" style="color:white;"><button  type="button" class="btn btn-info"><img src="{% static 'icon_sets\tag-solid.svg'%}" alt"" height="65" width="68" /><br />Samples</button></a>
          <a  href="{% url 'allflotation' %}"><button  type="button" class="btn btn-info"><img src="{% static 'icon_sets\flotation-solid.svg'%}" alt"" height="65" width="68" /><br />Flotation</button></a>
          <a  href="{% url 'speciesmanager' %}"><button  type="button" class="btn btn-info"><img src="{% static 'icon_sets\plant-hand.svg'%}" alt"" height="65" width="68" /><br />Taxon Manager</button></a>
        </div>
      </div>

      <div class="clearfix"></div>
      <!-- -ms-transform: matrix(1, 0, 0, 0.5, 0, -12.5); /* IE 9 */
      -webkit-transform: matrix(1, 0, 0, 0.5, 0, -12.5); /* Safari */
      transform: matrix(1, 0, 0, 0.5, 0, -12.5); /* Standard syntax */ -->
      <div id="time_test" style="height: 20px; min-width: 310px;"></div>
      <!-- <div id="lifeline" style="min-width: 310px; height: 50px; margin: 0 auto; "></div> -->
    </header>
    <!-- <div class='clearfix'></div> -->